### ISSUE TITLE
No webjars found on JBoss/Wildfly 9.0.1

### ISSUE THREAD

**Issue by chevdor** [webjars/webjars-locator#91] opened 2015-12-01 11:11 UTC
Using Wildfly 9.0.1, I made a project with a few webjars such as bootstrap.
I am using webjars-locator version 0.28 (from maven).

The following code returns 0:
````
WebJarAssetLocator assetLocator = new WebJarAssetLocator();
Map<String, String> loadedWebjars = assetLocator.getWebJars();
System.out.println("Webjars found: " + loadedWebjars.size());
````

Tthe method ````getFullPath(webjar, partialPath)```` also fails finding the path (which is probably related to the first problem).

Is there a workaround or a solution for this issue?

**Comment by jamesward** [comment] 2015-12-01 15:11
Duplicate of #18.

**Closed by jamesward** 2015-12-01 15:11 UTC
