### ISSUE TITLE
Doesn't work with springMVC

### ISSUE THREAD

**Issue by gaoyuan121** [webjars/webjars-locator#100] opened 2016-08-15 05:24 UTC
Hi guys,
I'm using SpringMVC 4.3.2 for developting but webjars-locator can't automatically configure the version information for my project. I add following lines in my spring configuration file:
 <mvc:resources mapping="/webjars/**" location="classpath:/META-INF/resources/webjars/"/>
mvc:annotation-driven/

The problem is that I can't visit my resource like : http://localhost:8080/webjars/bootstrap/js/bootstrap.min.js

Could you please show me a hint?

Thanks.

**Comment by jamesward** [comment] 2016-08-15 13:53
I'm not seeing anything about `<mvc:annotation-driven/>` in the docs: http://www.webjars.org/documentation#springmvc

Did you follow those instructions?

**Comment by utkuerd** [comment] 2017-01-17 15:46
I also have the same problem. Webjars works fine, I can access jquery through

https://localhost:8443/myapp/webjars/jquery/3.1.1-1/jquery.min.js

I've added webjars-locator latest version (0.32) from maven central repository to pom.xml as described in the docs. But no luck in resolving

https://localhost:8443/myapp/webjars/jquery/jquery.min.js

**Comment by jamesward** [comment] 2017-01-17 15:52
Might be similar issues as #102

**Comment by bheurter** [comment] 2017-01-17 16:04
We experienced the same issue with mvc:resources mapping.  
At the end, we solved it by declaring the mapping in java and not in XML : 

`@EnableWebMvc
@Configuration
public class WebConfig extends WebMvcConfigurerAdapter {

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {

        if (!registry.hasMappingForPattern("/webjars/**")) {
            registry.addResourceHandler("/webjars/**").addResourceLocations("classpath:/META-INF/resources/webjars/");
        }
        registry.setOrder(1);
    }
}
`

**Comment by utkuerd** [comment] 2017-01-17 16:26
To be clear I'm experiencing this issue with Spring Mvc (not SpringBoot) and I'm also using the same Java configuration method.

**Comment by philwebb** [comment] 2017-01-17 17:09
The `org.springframework.web.servlet.resource.WebJarsResourceResolver` class allows you to reference web-jar resources without including the version number. Check that you have the `webjars-locator` library on your classpath.

You can try adding a breakpoint in `org.springframework.web.servlet.config.annotation.ResourceChainRegistration.getResourceResolvers()` to see if the resolver is actually registered or not. If you think there's a bug in Spring can you raise a [JIRA](http://jira.spring.io) and provide a small sample application.

**Comment by utkuerd** [comment] 2017-01-17 19:22
I was able to diagnose the problem with your suggestion. The problem is `.springframework.web.servlet.config.annotation.ResourceChainRegistration.getResourceResolvers()` is not called at all. The calling method `org.springframework.web.servlet.config.annotation.ResourceHandlerRegistration.getRequestHandler()` calls this method only when a resource chain is registered in the configuration. Modifying the configuration as below solves the problem:

    registry.addResourceHandler("/webjars/**")
             .addResourceLocations("/webjars/")
             .resourceChain(false);

This is apparently not a webjar-locator problem. I'm not quite sure whether there is something wrong with Spring's way of handling webjar-locator resource handler or call to `resourceChain()` method should be necessary for configuration of webjar-locator.

**Comment by philwebb** [comment] 2017-01-17 22:45
Looking at the Javadoc, I'd say it's an intentional design decision:

> If this method is not invoked, by default only a simple PathResourceResolver is used in order to match URL paths to resources under the configured locations.

**Comment by jamesward** [comment] 2017-01-18 19:25
Is there something we need to add to our docs to help with this?

**Comment by jamesward** [comment] 2017-01-18 19:25
btw, thanks @philwebb for jumping in!

**Comment by utkuerd** [comment] 2017-01-18 19:36
I think it might be noted in Spring MVC docs that one needs to call one of the overloads of `resourceChain(..)` method if there is no explicitly configured Resource Handler registered. 

For XML configuration I guess the correct way is to use a  `<mvc:resource-chain resource-cache="false"></mvc:resource>`  tag pair, though I have not tried that myself. 

Btw, I found out Spring Boot resolved the same problem [in this issue](https://github.com/spring-projects/spring-boot/issues/4403). So I guess only Spring MVC is affected.

**Comment by jalbr74** [comment] 2017-11-27 23:19
I verified adding the following code solved the problem for me when configuring using XML.  

```
<mvc:resources mapping="/webjars/**" location="/webjars/">
	<mvc:resource-chain resource-cache="false" />
</mvc:resources>
```

Thanks @utkuerd

**Closed** 2017-11-27 23:32 UTC

**Comment by murukai** [comment] 2018-10-29 15:10
I am having an issue that the path at execution is appended the name of the applications so it cannot be found anyone please help. http://localhost:8080/contacts/webjars/jquery/3.3.1/jquery.min.js instead of http://localhost:8080/webjars/jquery/3.3.1/jquery.min.js
